# -*- coding: utf-8 -*-
"""Forecasting Assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iSC6e1Cv6UO5qg0Hw4tnImHW9B5X4m82
"""

#import statements
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier

#read in data

dtest = pd.read_csv("https://github.com/dustywhite7/Econ8310/raw/master/AssignmentData/assignment3.csv")
dtrain = pd.read_csv("https://github.com/dustywhite7/Econ8310/raw/master/AssignmentData/assignment3test.csv")

dtest.head(10)

#trying a boosted tree

Y = dtest['meal']
X = dtest.drop(['id','DateTime', 'Total', 'Discounts'], axis = 1)

x, xt, y, yt = train_test_split(X, Y, test_size=0.1, random_state = 42)

model = XGBClassifier(n_estimators = 50, max_depth = 5, learning_rate = 0.5, objective = 'binary:hinge')

modelFit = model.fit(x,y)

pred1 = model.predict(xt)

print(accuracy_score(yt, pred1)*100)

# Convert pred to a pandas Series
pred_series = pd.Series(pred)
display(pred_series)