# -*- coding: utf-8 -*-
"""Forecasting Assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iSC6e1Cv6UO5qg0Hw4tnImHW9B5X4m82
"""

#import statements
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier

#read in data

dtrain = pd.read_csv("https://github.com/dustywhite7/Econ8310/raw/master/AssignmentData/assignment3.csv")
dtest = pd.read_csv("https://github.com/dustywhite7/Econ8310/raw/master/AssignmentData/assignment3test.csv")

dtest.head(10)

#trying a boosted tree

Y = dtrain['meal']
X = dtrain.drop(['id','DateTime', 'Total', 'Discounts'], axis = 1)

x, xt, y, yt = train_test_split(X, Y, test_size=0.1, random_state = 42)

model = XGBClassifier(n_estimators = 50, max_depth = 5, learning_rate = 0.5, objective = 'binary:hinge')

model.fit(x,y)

# Validation accuracy
val_preds = model.predict(xt)
print("Validation Accuracy: ", accuracy_score(yt, val_preds) * 100)

# Prepare dtest with the same features
X_test = dtest.drop(['id','DateTime','Total','Discounts'], axis=1)

# Predictions on dtest
test_preds = model.predict(X_test)

# Convert predictions to a pandas Series, align with ids if you want
pred = pd.Series(test_preds, name="meal")
pred.head(10)